starSystems/Models/Planets.cs
using System.ComponentModel.DataAnnotations;

namespace starSystems.Models
{
    public class Planets
    {
        public int Id { get; set; }
        [Required]
        public string? Title { get; set; }
        [Required]
        public string? Description { get; set; }
        [Required]
        public int StarId { get; set; }
        [Required]
        public string? StarSystem { get; set; }
    }
}

starSystems/Controllers/PlanetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using starSystems.Data;
using starSystems.Models;

namespace starSystems.Controllers
{
    public class PlanetsController : Controller
    {
        private readonly PlanetsContext _context;

        public PlanetsController(PlanetsContext context)
        {
            _context = context;
        }

        // GET: planet
        public async Task<IActionResult> Index(string planetStarSystem, string searchString)
        {
            if (_context.Planets == null)
            {
                return Problem("Entity set 'PlanetContext.Planet'  is null.");
            }

            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from m in _context.Planets
                                            orderby m.StarSystem
                                            select m.StarSystem;

            var planet = from m in _context.Planets
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                planet = planet.Where(s => s.Title!.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(planetStarSystem))
            {
                planet = planet.Where(x => x.StarSystem == planetStarSystem);
            }

            var PlanetsStarSystemVM = new PlanetsStarSystemViewModel
            {
                starSystem = new SelectList(await genreQuery.Distinct().ToListAsync()),
                Planets = await planet.ToListAsync()
            };

            return View(PlanetsStarSystemVM);
        }

        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.planet.ToListAsync());
        //}

        // GET: planet/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var planets = await _context.Planets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (planets == null)
            {
                return NotFound();
            }

            return View(planets);
        }

        // GET: planet/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: planet/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,StarId,StarSystem")] Planets planets)
        {
            if (ModelState.IsValid)
            {
                _context.Add(planets);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(planets);
        }

        // GET: planet/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var planets = await _context.Planets.FindAsync(id);
            if (planets == null)
            {
                return NotFound();
            }
            return View(planets);
        }

        // POST: planet/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,StarId,StarSystem")] Planets planets)
        {
            if (id != planets.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(planets);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlanetsExists(planets.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(planets);
        }

        // GET: planet/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var planets = await _context.Planets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (planets == null)
            {
                return NotFound();
            }

            return View(planets);
        }

        // POST: planet/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var planets = await _context.Planets.FindAsync(id);
            if (planets != null)
            {
                _context.Planets.Remove(planets);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlanetsExists(int id)
        {
            return _context.Planets.Any(e => e.Id == id);
        }
    }
}

starSystems/Views/Planets/Create.cshtml
@model starSystems.Models.Planets

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Planets</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StarId" class="control-label"></label>
                <input asp-for="StarId" class="form-control" />
                <span asp-validation-for="StarId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StarSystem" class="control-label"></label>
                <input asp-for="StarSystem" class="form-control" />
                <span asp-validation-for="StarSystem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

starSystems/Views/Planets/Delete.cshtml
@model starSystems.Models.Planets

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Planets</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StarId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StarId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StarSystem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StarSystem)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

starSystems/Views/Planets/Details.cshtml
@model starSystems.Models.Planets

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Planets</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StarId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StarId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StarSystem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StarSystem)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

starSystems/Views/Planets/Edit.cshtml
@model starSystems.Models.Planets

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Planets</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StarId" class="control-label"></label>
                <input asp-for="StarId" class="form-control" />
                <span asp-validation-for="StarId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StarSystem" class="control-label"></label>
                <input asp-for="StarSystem" class="form-control" />
                <span asp-validation-for="StarSystem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

starSystems/Views/Planets/Index.cshtml
@model starSystems.Models.PlanetsStarSystemViewModel
@* @model IEnumerable<starSystems.Models.Planets>
 *@
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Planets" asp-action="Index" method="get">
    <p>
        <select asp-for="PlanetStarSystem" asp-items="Model.starSystem">
            <option value="">All</option>
        </select>

        Title: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Planets![0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Planets![0].Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Planets![0].StarId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Planets![0].StarSystem)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Planets!) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StarId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StarSystem)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>